CREATE_TABLE_HYPOXIA = """
CREATE TABLE IF NOT EXISTS hypoxia_table (
    id SERIAL PRIMARY KEY,
    time TIMESTAMP NOT NULL,
    value INT
);
"""

CREATE_TABLE_REGULAR = """
CREATE TABLE IF NOT EXISTS regular_table (
    id SERIAL PRIMARY KEY,
    time TIMESTAMP NOT NULL,
    value INT
);
"""
